[build]
  command = "npm run build"
  publish = "dist"  # Adjust this based on where your build output goes

[functions]
  directory = "../server/functions"  # Adjust the path to your serverless functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
