[build]
  command = "npm install && npm run build"  # Command to install and build your app
  publish = "dist"                          # Directory to publish your built frontend
  node_version = "20.16.0"                  # Specify your Node.js version here

[functions]
  directory = "../server/netlify/functions" # Path to your Netlify functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
