name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Cache client dependencies
        uses: actions/cache@v3
        with:
          path: ./client/node_modules
          key: ${{ runner.os }}-client-node-modules-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-client-node-modules-

      - name: Install dependencies for client
        working-directory: ./client
        run: npm install

      - name: Cache server dependencies
        uses: actions/cache@v3
        with:
          path: ./server/node_modules
          key: ${{ runner.os }}-server-node-modules-${{ hashFiles('server/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-node-modules-

      - name: Install dependencies for server
        working-directory: ./server
        run: npm install

      - name: Ensure Jest is executable
        run: chmod +x ./server/node_modules/.bin/jest

      - name: Run tests for client
        working-directory: ./client
        run: npm test -- --passWithNoTests

      - name: Run tests for server
        working-directory: ./server
        run: npm test
